import { createAdvancedChapter } from '@/content/advanced-content-helpers';

export const chapterTwelve = createAdvancedChapter({
  id: 12,
  contentVersion: 3,
  flashcardVersion: 4,
  title: 'Inter-VLAN Routing',
  summary: 'Use router subinterfaces and one 802.1Q trunk to route safely between VLAN networks.',
  lessons: [
    {
      id: 'inter-vlan-routing-need',
      title: 'Different VLANs need a Layer 3 crossing',
      illustration: 'inter-vlan-boundary',
      body: 'VLAN 10 and VLAN 20 are separate Layer 2 broadcast domains. A switch can forward inside either VLAN, but it cannot move an ordinary frame directly from one domain into the other. Communication between the two networks needs a Layer 3 device that can receive traffic from one VLAN, make an IPv4 routing decision, and send new Layer 2 traffic into the destination VLAN.',
      sections: [
        { heading: 'Separation remains useful', body: 'Routing does not merge the VLANs. Broadcasts and unknown unicasts remain confined to their original VLAN.' },
        { heading: 'The router crosses deliberately', body: 'Only traffic addressed to a suitable gateway and supported by the routing configuration crosses the boundary.' },
      ],
      example: { label: 'VLAN 10 TO VLAN 20', setup: 'PC-A in VLAN 10 wants to reach PC-B in VLAN 20. Their IPv4 networks are 192.168.10.0/24 and 192.168.20.0/24.', result: 'PC-A sends toward its gateway; a router, not the access switch alone, performs the network-to-network forwarding.' },
      takeaway: 'Inter-VLAN communication is Layer 3 forwarding between separate Layer 2 domains.',
    },
    {
      id: 'gateway-per-vlan',
      title: 'Each VLAN uses a gateway in its own subnet',
      illustration: 'vlan-gateway',
      body: 'A host can send remote traffic only to a next hop it can reach on its local LAN. PC-A therefore uses 192.168.10.1 in VLAN 10, while PC-B uses 192.168.20.1 in VLAN 20. Both addresses may belong to the same physical router, but they represent separate logical router interfaces and separate connected networks.',
      sections: [
        { heading: 'Local first hop', body: 'PC-A resolves the MAC address for 192.168.10.1 because that gateway belongs to PC-A’s own 192.168.10.0/24 subnet.' },
        { heading: 'Do not borrow the other gateway', body: '192.168.20.1 is not a usable gateway for PC-A because PC-A cannot reach it as a local 192.168.10.0/24 neighbor.' },
      ],
      example: { label: 'TWO LOCAL GATEWAYS', setup: 'PC-A is 192.168.10.10/24 with gateway 192.168.10.1. PC-B is 192.168.20.20/24 with gateway 192.168.20.1.', result: 'Each PC reaches a gateway address inside its own VLAN and subnet.' },
      takeaway: 'Every endpoint gateway must be reachable inside that endpoint’s local VLAN and IPv4 subnet.',
      checkpoint: { prompt: 'Which gateway is valid for PC-A at 192.168.10.10/24?', correctChoiceId: 'local', choices: [
        { id: 'local', label: '192.168.10.1', feedback: 'Correct. The gateway shares PC-A’s local 192.168.10.0/24 network.' },
        { id: 'remote', label: '192.168.20.1', feedback: 'That address belongs to the remote VLAN 20 subnet, so PC-A cannot use it as its local first hop.' },
        { id: 'host', label: '192.168.20.20', feedback: 'That is the remote host, not a router interface reachable on PC-A’s local network.' },
      ] },
    },
    {
      id: 'router-on-a-stick-topology',
      title: 'One router link can serve several VLANs',
      illustration: 'router-on-stick',
      body: 'Router-on-a-stick uses one physical router interface connected to a switch trunk. The trunk carries frames for several VLANs while preserving each VLAN identity with 802.1Q information. Logical router subinterfaces divide that one physical connection into separate Layer 3 attachment points, one for each modeled VLAN network.',
      sections: [
        { heading: 'One cable, several contexts', body: 'The router and switch share one Ethernet cable, but VLAN 10 and VLAN 20 frames remain distinguishable on it.' },
        { heading: 'The switch side must be a trunk', body: 'An access port carries only one endpoint VLAN and cannot deliver both tagged VLAN contexts to the router.' },
      ],
      example: { label: 'SHARED ROUTER LINK', setup: 'SW-1 F0/24 connects to R-1 G0/0. F0/24 is a trunk allowing VLAN 10 and VLAN 20.', result: 'Both VLANs reach the router over one physical link without becoming one Layer 2 network.' },
      takeaway: 'Router-on-a-stick combines a switch trunk with logical router subinterfaces.',
    },
    {
      id: 'dot1q-router-subinterfaces',
      title: 'A subinterface terminates one VLAN context',
      illustration: 'router-subinterface',
      body: 'A router subinterface is a logical child of a physical interface. G0/0.10 uses 802.1Q VLAN 10 and address 192.168.10.1/24. G0/0.20 uses VLAN 20 and address 192.168.20.1/24. The subinterface number is a readable convention here; the encapsulation command is what associates the logical interface with a VLAN.',
      sections: [
        { heading: 'The physical parent stays active', body: 'G0/0 owns the cable and must be enabled. The logical subinterfaces inherit that physical link rather than receiving separate cables.' },
        { heading: 'Tags must be unique on the parent', body: 'Two subinterfaces on G0/0 cannot both terminate VLAN 10 in this bounded model because the arriving tag would not identify one unambiguous Layer 3 interface.' },
      ],
      example: { label: 'BUILD TWO LOGICAL INTERFACES', setup: 'R-1 begins with enabled physical interface G0/0 and no IPv4 address on that parent.', presentation: 'guided', visual: { illustration: 'router-subinterface', stageIds: ['select', 'tag', 'address', 'enable'] }, steps: [
        { id: 'select', label: 'SELECT THE LOGICAL INTERFACE', explanation: 'Enter interface G0/0.10 so VLAN 10 receives a logical Layer 3 attachment.' },
        { id: 'tag', label: 'ASSOCIATE VLAN 10', explanation: 'Encapsulation dot1q 10 tells the router which tagged frames belong to this subinterface.' },
        { id: 'address', label: 'ASSIGN THE GATEWAY', explanation: '192.168.10.1/24 becomes the local gateway and creates a connected route for 192.168.10.0/24.' },
        { id: 'enable', label: 'VERIFY THE PARENT', explanation: 'G0/0 and the switch trunk must be active for G0/0.10 to operate.' },
      ], result: 'Repeat the same pattern for G0/0.20, VLAN 20, and 192.168.20.1/24.' },
      takeaway: 'A logical subinterface combines one VLAN tag with one IPv4 gateway network.',
    },
    {
      id: 'inter-vlan-forwarding-sequence',
      title: 'Routing rebuilds the Ethernet frame',
      illustration: 'inter-vlan-forwarding',
      body: 'The IP destination remains PC-B throughout the trip, but Ethernet delivery and VLAN context change. PC-A first builds an untagged access frame for its VLAN 10 gateway. SW-1 adds VLAN 10 context on the trunk; R-1 terminates that framing, routes the IPv4 packet, and creates a different VLAN 20 delivery.',
      sections: [
        { heading: 'ARP follows the next hop', body: 'PC-A resolves 192.168.10.1, not PC-B, because the remote destination is outside PC-A’s local subnet.' },
        { heading: 'The router processes and rebuilds', body: 'R-1 removes the incoming Ethernet framing, reduces IPv4 TTL, selects connected route 192.168.20.0/24, and resolves PC-B if necessary. It then builds a new Ethernet frame through G0/0.20; the trunk carries VLAN identifier 20.' },
      ],
      example: { label: 'PC-A SENDS TO PC-B', setup: 'PC-A sends from 192.168.10.10 to 192.168.20.20 through R-1.', presentation: 'guided', visual: { illustration: 'inter-vlan-forwarding', stageIds: ['gateway', 'tag-in', 'route', 'tag-out', 'reply'] }, steps: [
        { id: 'gateway', label: 'CHOOSE THE GATEWAY', explanation: 'PC-A sees a remote /24 and chooses 192.168.10.1 as its next hop.' },
        { id: 'tag-in', label: 'ADD VLAN 10 ON THE TRUNK', explanation: 'SW-1 adds 802.1Q VLAN identifier 10 while carrying the frame to G0/0.10.' },
        { id: 'route', label: 'TERMINATE AND ROUTE', explanation: 'R-1 removes the incoming frame, reduces TTL, and matches 192.168.20.20 to connected network 192.168.20.0/24.' },
        { id: 'tag-out', label: 'BUILD VLAN 20 DELIVERY', explanation: 'After resolving PC-B, R-1 creates new Ethernet framing. The trunk carries it with VLAN identifier 20 before SW-1 sends an untagged access frame to PC-B.' },
        { id: 'reply', label: 'VERIFY THE RETURN', explanation: 'PC-B sends its reply through 192.168.20.1, and R-1 routes back to VLAN 10.' },
      ], result: 'The Echo round trip succeeds only when both VLAN paths and both gateway directions work.' },
      takeaway: 'Routers preserve IP endpoints while replacing link-layer information at the VLAN boundary.',
    },
    {
      id: 'inter-vlan-configuration-workflow',
      title: 'Configure and verify in a reliable order',
      illustration: 'inter-vlan-config',
      body: 'A reliable workflow starts at Layer 2 and then adds Layer 3. Create the VLANs and access memberships, establish the allowed trunk, enable the router parent, configure one tagged subinterface and gateway per VLAN, then verify interfaces and connected routes before pinging. This order keeps each test focused and makes a failure easier to locate.',
      sections: [
        { heading: 'Inspect before ping', body: 'Show commands can reveal a missing VLAN allowance, an unassigned subinterface, or a down physical parent without reducing every failure to “ping failed.”' },
        { heading: 'Verify both directions', body: 'A forward request without a usable return path is not a successful round trip.' },
      ],
      example: { label: 'EVIDENCE CHECKLIST', setup: 'The access ports are already assigned. The router trunk and subinterfaces still need configuration.', presentation: 'guided', visual: { illustration: 'inter-vlan-config', stageIds: ['trunk', 'subinterfaces', 'routes', 'test'] }, steps: [
        { id: 'trunk', label: 'VERIFY THE TRUNK', explanation: 'F0/24 must use trunk mode and allow VLAN 10 and VLAN 20.' },
        { id: 'subinterfaces', label: 'CONFIGURE BOTH GATEWAYS', explanation: 'Add G0/0.10 and G0/0.20 with matching tags and /24 gateway addresses.' },
        { id: 'routes', label: 'READ CONNECTED ROUTES', explanation: 'Show IP route should list 192.168.10.0/24 and 192.168.20.0/24 as connected.' },
        { id: 'test', label: 'TEST BOTH HOSTS', explanation: 'Ping PC-B from PC-A and PC-A from PC-B to confirm the modeled return path.' },
      ], result: 'State-based verification accepts any valid command order, but the checklist provides a dependable troubleshooting path.' },
      takeaway: 'Verify VLAN carriage, subinterface state, connected routes, and the return path.',
    },
    {
      id: 'inter-vlan-troubleshooting',
      title: 'Troubleshoot the first broken boundary',
      illustration: 'inter-vlan-troubleshooting',
      body: 'An inter-VLAN ping depends on several distinct conditions, so “the router is broken” is rarely a useful first conclusion. Start with the source address and gateway, then inspect access membership, the allowed trunk VLAN, the matching router tag and address, the physical parent, the connected route, and finally the return side. Each observation should narrow the next check.',
      sections: [
        { heading: 'Physical link without VLAN carriage', body: 'A cable may be up while VLAN 20 is absent from the trunk allowed list. Physical connectivity alone does not prove that VLAN context can cross.' },
        { heading: 'Correct tag with wrong gateway network', body: 'Encapsulation VLAN 20 does not repair a subinterface addressed in 192.168.30.0/24 when the hosts use 192.168.20.0/24.' },
      ],
      example: { label: 'VLAN 10 WORKS / VLAN 20 FAILS', setup: 'G0/0 is up and VLAN 10 succeeds, but VLAN 20 cannot reach its gateway.', result: 'Inspect VLAN 20 access membership, trunk allowance, G0/0.20 encapsulation, and 192.168.20.1/24 before changing unrelated routes.' },
      takeaway: 'Follow the dependency chain and act on the first specific failed condition.',
      checkpoint: { prompt: 'The physical trunk is up, but VLAN 20 is not allowed on it. What fails first?', correctChoiceId: 'carriage', choices: [
        { id: 'carriage', label: 'VLAN 20 CARRIAGE TO THE ROUTER', feedback: 'Correct. The cable exists, but the trunk configuration blocks VLAN 20 before its router subinterface can receive the frame.' },
        { id: 'merge', label: 'VLAN 10 AND 20 MERGE', feedback: 'A blocked allowed list does not merge VLANs; it prevents the omitted VLAN from crossing the trunk.' },
        { id: 'dns', label: 'DNS NAME RESOLUTION', feedback: 'This test uses direct IPv4 addressing, and the first demonstrated failure is VLAN carriage below DNS.' },
      ] },
    },
  ],
  questions: [
    { lessonId: 'inter-vlan-routing-need', prompt: 'Why can an access switch not directly deliver an ordinary VLAN 10 frame into VLAN 20?', answers: ['The VLANs are separate Layer 2 domains and need Layer 3 forwarding', 'The destination MAC is always a broadcast', 'Every switch port requires a public IPv4 address'], correctAnswerIndex: 0, explanation: 'Routing provides the deliberate Layer 3 crossing without merging the broadcast domains.' },
    { lessonId: 'gateway-per-vlan', prompt: 'PC-A is 192.168.10.10/24. Which router address is a valid local gateway?', answers: ['192.168.10.1', '192.168.20.1', '192.168.20.20'], correctAnswerIndex: 0, explanation: 'A host gateway must be reachable in the host’s local subnet.' },
    { lessonId: 'router-on-a-stick-topology', prompt: 'What must the switch link toward a router-on-a-stick carry?', answers: ['The required tagged VLAN contexts', 'Only one untagged endpoint VLAN', 'No Ethernet frames'], correctAnswerIndex: 0, explanation: 'The shared router link is a trunk carrying the required VLANs.' },
    { lessonId: 'dot1q-router-subinterfaces', prompt: 'What associates G0/0.20 with VLAN 20?', answers: ['Its 802.1Q encapsulation VLAN setting', 'The number 20 in its name alone', 'PC-B’s hostname'], correctAnswerIndex: 0, explanation: 'The encapsulation setting, not the cosmetic subinterface number, selects the VLAN context.' },
    { lessonId: 'inter-vlan-forwarding-sequence', prompt: 'PC-A sends to remote PC-B. Which MAC does PC-A resolve first?', answers: ['Its VLAN 10 gateway MAC', 'PC-B’s remote MAC directly', 'Every switch MAC in the path'], correctAnswerIndex: 0, explanation: 'Remote traffic is framed for the local next-hop gateway.' },
    { lessonId: 'inter-vlan-forwarding-sequence', prompt: 'Which VLAN identifiers appear on the router trunk when PC-A in VLAN 10 reaches PC-B in VLAN 20?', answers: ['VLAN 10 toward the router, then VLAN 20 toward PC-B', 'VLAN 20 in both directions before routing', 'No VLAN context anywhere'], correctAnswerIndex: 0, explanation: 'The router terminates the source VLAN context and builds new link-layer delivery in the destination VLAN.' },
    { lessonId: 'inter-vlan-configuration-workflow', prompt: 'Which evidence should appear after both /24 subinterfaces are operational?', answers: ['Two corresponding connected routes', 'One merged VLAN broadcast domain', 'A dynamic route learned from DNS'], correctAnswerIndex: 0, explanation: 'Operational addressed subinterfaces derive connected routes for both VLAN networks.' },
    { lessonId: 'inter-vlan-troubleshooting', prompt: 'VLAN 10 works, VLAN 20 fails, and VLAN 20 is missing from the trunk allowed list. What should be corrected first?', answers: ['Allow VLAN 20 on the router trunk', 'Replace both host IPv4 addresses', 'Add a DNS server'], correctAnswerIndex: 0, explanation: 'The known first failure is the blocked Layer 2 VLAN path.' },
  ],
  cards: [
    ['inter-vlan-routing-need', 'Why can hosts in VLAN 10 and VLAN 20 not communicate through Layer 2 switching alone?', 'They belong to separate Layer 2 broadcast domains, so traffic between their IPv4 networks requires a router.', 'The router becomes the Layer 3 boundary between the VLANs.'],
    ['gateway-per-vlan', 'What gateway should PC-A at 192.168.10.10/24 use, and why?', '192.168.10.1, because the gateway interface must be reachable inside PC-A’s own 192.168.10.0/24 subnet.', 'PC-B in 192.168.20.0/24 uses a different gateway interface, 192.168.20.1.'],
    ['router-on-a-stick-topology', 'What physical connection defines a router-on-a-stick topology?', 'One router physical interface connects to a switch trunk that carries multiple VLANs.', 'Logical router subinterfaces separate the VLAN contexts on that shared cable.'],
    ['dot1q-router-subinterfaces', 'What three key settings make router subinterface G0/0.10 serve VLAN 10?', 'An 802.1Q encapsulation VLAN of 10, a valid VLAN 10 gateway address and prefix, and an active physical parent interface.', 'The switch trunk must also permit VLAN 10.'],
    ['inter-vlan-forwarding-sequence', 'PC-A in VLAN 10 sends to PC-B in VLAN 20. What IPv4 next hop does PC-A choose first?', 'PC-A chooses its VLAN 10 default gateway, 192.168.10.1.', 'The remote destination remains 192.168.20.20, but the first Ethernet frame targets the gateway MAC.'],
    ['inter-vlan-forwarding-sequence', 'What exact Layer 2 transition occurs when routing from VLAN 10 to VLAN 20?', 'The router terminates the VLAN 10 frame, processes and routes IPv4, then builds a new frame carried with VLAN identifier 20 toward PC-B.', 'The end-to-end IPv4 endpoints remain PC-A and PC-B while TTL and link-layer delivery are processed.'],
    ['inter-vlan-configuration-workflow', 'Which connected routes should appear when G0/0.10 and G0/0.20 are correctly operational?', '192.168.10.0/24 through G0/0.10 and 192.168.20.0/24 through G0/0.20.', 'Operational addressed subinterfaces let the router derive both routes automatically.'],
    ['inter-vlan-configuration-workflow', 'What switch configuration must match the router subinterfaces?', 'The router-facing port must be a trunk that permits VLANs 10 and 20, while the PC ports must be access ports in their correct VLANs.', 'Both sides must agree on which VLAN context each frame carries.'],
    ['inter-vlan-troubleshooting', 'VLAN 10 works but VLAN 20 is blocked on the router-facing trunk. What should you fix first?', 'Permit VLAN 20 on the trunk before changing unrelated host or routing settings.', 'Troubleshooting starts at the first known failed dependency.'],
    ['inter-vlan-troubleshooting', 'Why must inter-VLAN verification test both directions?', 'The request path can work while a gateway, VLAN path, interface, or return configuration still prevents the reply.', 'Successful two-way testing confirms both routed directions for that scenario.'],
  ],
  lab: ['inter-vlan-routing-desk', 'Route between two VLANs', 'Configure the trunk and router subinterfaces, then verify both directions'],
  recap: ['A working router-on-a-stick path between VLAN 10 and VLAN 20', 'Gateways, tagged subinterfaces, frame replacement, verification, and troubleshooting', 'Use the sandbox to modify and test a complete inter-VLAN network'],
});
